### ISSUE TITLE
Hash pin Github Workflows

### ISSUE THREAD

**Issue by joycebrum** [libexif/libexif#106]
## Description

I would like to suggest a security practice recommended by the [OpenSSF Scorecard][scorecard-repo] which is to hash pin dependencies to prevent dependency-confusion, typosquatting and tag renaming attacks. 

The change would only be applied to GitHub workflows, dockerfiles and shell scripts dependencies. This means hash pinning GitHub Workflow actions.

Along with hash-pinning dependencies, I also recommend adopting dependabot or renovatebot to help keep the dependencies up to date. Both tools can update  hashes and associated semantic version comments. 

Together with this issue I'll also suggest the PRs with the changes since they are quite simple. 

Any questions or concerns just let me know.
Thanks!

## Additional Context

A tag renaming attack is a type of attack whereby an attacker:
- Hijack an action.
- Upload a malicious version.
- Replace existing tags with malicious versions.

A [typosquatting attack][typosquatting] is a type of attack whereby an attacker:
- Create a malicious package
- Publish it with a similar name of a known package (example: numpi instead of numpy)

For more informations about the dependency-update tools:
- [Dependabot][dependabot]
- [Renovatebot][renovatebot]

[scorecard-repo]: https://github.com/ossf/scorecard
[deps-confusion]: https://www.websecuritylens.org/how-dependency-confusion-attack-works-and-how-to-prevent-it/ 
[typosquatting]: https://snyk.io/blog/typosquatting-attacks/ 
[dependabot]: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
[renovatebot]:https://www.mend.io/renovate/

**Comment by dfandrich** [comment]
I don't understand how this improves security. We are already at the mercy of the owners of those actions, who can not only move labels but change the code to do whatever they want. Pinning these dependencies does nothing to change that. All this would do int he case of an attack is to pin our dependencies to a malicious version. A typosquatting attack is also not relevant since these are existing actions. In fact, this change could even increase the attack surface since we not depend on a brand-new bot that changes our code. I see no benefit to this change to this project.

**Comment by dfandrich** [comment]
@msmeissn, what's your opinion?

**Comment by msmeissn** [comment]
The actual hash could avoid hijacked actions, (but could they perhaps even specify the hash as textual tag?)

So I think it gains some security.

dependabot has no write perms here, so it will do pull requests. (and it seems more established bot already ... although if attackers can hijack that bot it will be very scary for github)

**Comment by msmeissn** [comment]
FWIW I would tend to have it

**Comment by dfandrich** [comment]
I'd like to hear the story of how this has any positive security impact on libexif. Anyone who can push a label can push bad code, so pinning by actions is no improvement in that scenario. And if someone malicious can create a bad release without being able to change the code, then one of two things is most likely to happen: 1) someone will notice and fix the release before any of our actions are run, or 2) nobody notices and Dependabot pins our actions to a bad release. This doesn't help libexif either way.

All I see this doing is causing 90% of the commit history to be dependabot commits, and hundreds of open pull requests as we get tired of approving 3 PRs a week on a project that has averaged 0.35 legitimate pull requests per week since moving to Github.

**Comment by joycebrum** [comment]
Hi @dfandrich thanks for the return.

The main benefit of hash pining (either used on github actions either on pip/choco/npm installs) is to ensure that the code running is the same that was considered trustfull initially and that it wasn't corrupted anyway (by using a tag renaming attack for example).

That said it is even more important to hash pin (ensure the version running is the reliable one) considering that the actions has many permissions on the repo.

The dependabot role here is to ensure that this hash pinning won't increase the maintainance work, but it does not need to be 3 times a week, it can 1 for example. It is just to allow you to easily update if you want and keep the hash pinning format.

**Comment by dfandrich** [comment]
Thanks for the response. But, you still haven't answered my points. Regarding "to ensure that the code running is the same that was considered trustfull initially", "initially" refers to the time that the pinner runs, which could be before *or after* a malicious tag update. My point is that we don't know that "the version running is the reliable one" because it could have just as easily been pinned to a bad version as a good one.

Even dropping to 1 pinner run a week means that there will still be 3× the number of commits for pinning PRs than legitimate PRs.

**Comment by msmeissn** [comment]
The UI of what your are doing is contra-intuitive I have to admit:

- the initial setup is done from the Security drop down menu on the github project page. 
  - This is super easy and without need for specific configuration.
    
- there is then a need to enable a bot and accept pull requests from it.
  - this is entire different method to adjust it.

So it is a bit weird that this is not handled by Github itself with a better UI.

**Comment by joycebrum** [comment]
Hi, sorry for the delay -- I'm trying to understand why sometimes GitHub does not notify me about new comments 😓 .

> "initially" refers to the time that the pinner runs

yeah, it refers to the last time a version was considered safe enough to run on libexif -- receiving manual approve to upgrade the version. 

> My point is that we don't know that "the version running is the reliable one" because it could have just as easily been pinned to a bad version as a good one.

We are not totally sure because a malicious version can slipped in,  but we will certainly not blindly upgrade to a malicious version. The idea is that we will mitigate the risk of having the CI running on a malicious version by manually upgrading through PRs.

The idea on having this upgrade happening through PRs suggested by either dependabot or renovatebot has the following benefits:

- the bot has some previous analysis on the version -- trying to first see if it is stable and compatible.
- it usually delays to suggest the upgrade (except for security releases) in order to give time to vulnerabilities to be identified and fixed before you even being notified. This is better than the blind upgrade when using major, which will expose libexif to the vulnerability once it is released.  
- pinning to a fix version (either by hash pinning or by patch version pinning) ensures CI stability, preventing from random breaks caused by breaking changes.

The additional safety hash pin provide in comparison with patch version pinning (v1.1.1 for example) is that the project won't be affect by tag renaming attacks because the version running will be immutable. 

> So it is a bit weird that this is not handled by Github itself with a better UI.
Since this is a known concern when using GitHub Actions, GitHub was working on making GitHub Releases immutable by default, but after the layoffs it seems to be deprioritized. 

Now the status is "for the Future" so we have no idea when this will be done.

---------------
Additional info:

Renovatebot allows collapsing the version upgrades to single PR, this can reduce the number of PRs and make it easier to review and upgrade versions.
