### ISSUE TITLE
exif_convert_uft16_to_utf8 broken on big-endian machines

### ISSUE THREAD

**Issue by th-otto** [libexif/libexif#22]
If i understand the specification correctly, UTF16 in Exif always means UTF16-LE. However, exif_convert_uft16_to_utf8 always accesses the data in host endian format, producing garbage when running on big-endian machines.

**Comment by th-otto** [comment]
Edit: i also found a problem in the exif tool regarding big-endian machines (in action.c, the address of p->use_ids is passed to callbacks; this is an unsigned int, but accessed through an unsigned char pointer). But i can't open issues there.

**Comment by dfandrich** [comment]
Can you point to a source for the assertion that UNICODE means UTF16-LE? I was
never able to find that in the specs.

**Comment by th-otto** [comment]
No, sorry, but the test in https://github.com/libexif/libexif/blob/6b9dd85fbf14bde976585d6a0996944b0d505a97/test/test-value.c#L125  seems to assume that.

And the function in https://github.com/libexif/libexif/blob/6b9dd85fbf14bde976585d6a0996944b0d505a97/libexif/exif-entry.c#L1378-1390 does not check the endianness at all.

**Comment by dfandrich** [comment]
The function exif_convert_utf16_to_utf8 is used in only one place, to convert the Microsoft proprietary EXIF_TAG_XP_* tag data. This, as far as I can tell, is always going to be UCS-2LE (which the comment for that function explains).  But, you're right, the function assumes that it will be run on a little endian machine, so that comment is currently wrong. I think the code should be fixed to match the comment.

**Comment by th-otto** [comment]
Yes, the data might be in LE, but it might also be *extracted* on big-endian machines.
