### ISSUE TITLE
[QUESTION] What needs to be done to make this project Windows friendly?

### ISSUE THREAD

**Issue by levicki** [libexif/libexif#25]
Let me quote a bit of text from [README-Win32.txt](https://github.com/libexif/libexif/blob/f87fba7b1edfe1ea664110825a6f2ac92a85960c/README-Win32.txt#L8-L9):
```
hack yourself a build system somehow
      This seems to be the Windows way of doing things.
```
First of all, this kind of snark is not only inaccurate, but also highly unprofessional and in my humble opinion it should not be in the official documentation of any project.

There are several options for building anything on Windows:

1. You can simply download and install [Visual Studio 2019 Community](https://visualstudio.microsoft.com/vs/) which is free to use, and create the relevant project and solution files.

2. You can download [Build Tools for Visual Studio 2019](https://aka.ms/buildtools), manually create XML project file as documented here in [MSBuild documentation](https://docs.microsoft.com/en-us/cpp/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project?view=vs-2019), and build from command line without the need for Visual Studio.

3. You can switch your project build system to CMake which is directly supported in Visual Studio 2019. CMake can generate project files for Windows platform given enough instructions.

So no, the Windows way of doing things is not "hacking yourself a build system somehow".

Now the question is, are the authors and maintainers of this project willing to make (or at least allow) any changes to the project that would make it Windows friendly by providing default VS 2019 project and solution files? Note that this doesn't have to be supported or maintained, just be there for the rest of us to use as a starting point.

Please advise.

**Comment by ndim** [comment]
[ Note that I can only speak for myself here. I do not speak for current libexif maintainer Dan. ]

I absolutely agree that README-Win32.txt could use an update after 14 years of being kept around untouched. Quite a few things have changed since then, both technical things and political things: We have 64bit Windows now, and Microsoft are distributing Linux userlands for Windows instead of considering all Free Software a cancer.

The last time I have actually developed and compiled on a Windows system was in 2003, and that experience is what my 2005 efforts to make libexif build on/for Windows were based on.

libexif uses (and was using back in 2005 when README-Win32.txt was written) an Automake based build system which is capable of building libexif on and/or for a huge number of different platforms. Back in 2005, mingw32 and msys were two options to build libexif with its Automake based buildsystem on/for Windows. At least mingw32 and mingw64 still exist today in 2019.

However, as your three enumeration points confirm, the common way of doing things on Windows to this day usually does not involve Automake. Your first two enumeration points even elaborate on  writing/developing/hacking/whatever-you-want-to-call-it a new libexif build system to work with common  proprietary Windows-only software. The two parallel build systems within the libexif source tree would definitely need some manual maintainance to stay in sync. So you are actually confirming what I have written back in 2005, and not all that much appears to have changed in the usual ways of doing things on Windows.

If your issue is with the term "hack" - having two parallel sets of build system files within one project to be kept in sync manually certainly is a less than elegant technical solution. If you consider 2005 hobbyist developer me calling that a hack unprofessional, you might want to keep in mind this was written in a time when Microsoft's professionally professional bosses professionally called Linux and all Free Software (which includes libexif) a "cancer" and acting accordingly.

With Microsoft's efforts of recent years to make Windows more compatible with Linux and the whole Free/Open Source software ecosystem, I imagine it should have become easier (at least on the technical side) to provide a library such as libexif in a way that it can build both on unixoid and on/for Windows systems.

Whether that involves libexif adding a Visual Studio specific set of build system files, libexif switching to cmake, or whether Microsoft have provided something which integrates better with Automake so Windows users can more easily use libexif's existing build system (Didn't Microsoft start providing a GNU userland to run natively on Windows relatively recently?), I do not know.

If such VS specific files are relatively simple to use text files, there might even be a way to at least add an automatic consistency check when e.g. source files are added or removed.

However, parts of libexif rely on system properties detected by the `configure` script and put into a file `config.h`, which VS would not know how to create. So you would need to manually write a VS specific `config.h` which would only be referenced by the VS specific build system files, and then keep that in sync with whatever new system features are added to `configure.ac`. Other similar cases might exist where the Automake based build system uses scripts, at least the results of which would need to be statically added for VS builds.

There are just a few ideas of mine. You will have to talk to Dan about implementing any of this in libexif.

**Comment by levicki** [comment]
First of all, thanks for a detailed reply. Allow me to clarify a few bits:

> Your first two enumeration points even elaborate on writing/developing/hacking/whatever-you-want-to-call-it a new libexif build system to work with common proprietary Windows-only software.

It goes without saying that build on Windows, for the sake of interoperability with other code written for Windows platform, should be done using Microsoft Visual C++ compiler.

Both Visual Studio 2019 Community and Build Tools for Visual Studio 2019 are ways for obtaining said compiler chain, with the sole difference that the latter will also require Windows SDK, which is already included in the former.

True, common way to work on Windows is to have solution (.sln) and project (.vcxproj) files. They would be an equivalent of a Linux makefile, and both Visual Studio and MSBuild (which Visual Studio uses internally) depend on them for building the project.

> So you are actually confirming what I have written back in 2005, and not all that much appears to have changed in the usual ways of doing things on Windows.

I am not -- I was simply enumerating the various ways to create necessary project files for Windows platform. I have used a variety of open-source projects in my personal (non-commercial) projects, and most of them provide Visual Studio project files with various degrees of support for it.

Some provide them in the `cotrib` folder as is (generated by Visual Studio or manually), and leave the potential users to figure out when something doesn't work. They do accept pull requests for fixes, but are not actively maintaining those files unless there is a need to add new source files to the project.

Others range from using `perl` scripts to generate project files (like OpenSSL), to using CMake as their build system which handles creation of Visual Studio project files and any system-specific `config.h`, and keeping things in sync for them.

My personal suggestion would therefore be to migrate to CMake because it is the only well-supported multi-platform build system.

Of course, I almost expect to hear "Why would we change something that works?" and here is my rationale.

Back in January 2016 I went through the process of making a custom build of libexif 0.6.21 for Windows. Creating `config.h` was the easiest part, but if I remember correctly, creating a project did require quite a bit of source reorganizing and some editing.

Almost four years later (I am taking the liberty to paraphrase what you said above) "and not all that much appears to have changed" -- this project is still not Windows friendly.

Yes, Microsoft did a lot of bad things in the past, but developers working on that platform didn't, and in my opinion they don't deserve this almost hostile attitude. We should all move forward and accept new technologies and new levels of collaboration with open mind when possible instead of remaining frozen in the 1990s.

**Comment by dfandrich** [comment]
I'll have to agree with all that ndim has to say. I've worked on projects that had two parallel build systems and it's a recipe for pain. Users assume that they can choose either one, but one inevitably atrophies due to its lower popularity among users and developers which results in subtle problems at build or run time. I would not like to inflict that pain on the few developers and the (many more) users of libexif. Last time I looked at CMake, the benefits over autoconf were so marginal as to be not worth considering (although, I understand it has matured considerably since then).

We do have several CI builds in three different Windows environments to help avoid basic Windows regressions but even these are more limited than the other environments due to lack of anyone to make them better. My understanding of building on Windows is that one or more of those methods (not including a Windows cross-compiler build which ought to also work) can be used to build a libexif library that's usable in other Windows projects.

In my search for alternative Windows build mechanisms, I've run into two options that looked promising. One apparently extends autoconf to add a `--enable-msvcdsp` option that creates MSVC build files as the output (I haven't found any more details on that one). Another is the [Unix cc compiler to Microsoft cl compiler wrapper](https://github.com/swig/cccl) (which looked mothballed for a long time but has had some activity lately). I'd be more interested in a solution like those over maintaining a parallel build system. It will also be a hard sell to wholesale replace the current one.

**Comment by levicki** [comment]
@dfandrich Thanks for your response.

Unfortunately, the problem with sticking with GNU autotools is that it makes it necessary to install either Cygwin (which is a PITA to put it bluntly), or to enable Windows Subsystem for Linux (not all users have the necessary admin rights to do it) and then install your Linux distro of choice from Windows Store (which is disabled in many corporate environments) or manually (somewhat complicated and error prone and also depends on whether application sideloading is enabled by your organization) and then on top of that use a cludge like cccl and hope it will all click together.

On the other hand CMake is natively supported on all platforms, and has good integration with and support for Visual Studio. I understand that it is a hard sell, but on the other hand, "selling" GNU autotools in 2019 to developers who might want to use your project and contribute to it doesn't look much easier sell to me. Most people will just turn to other projects such as TinyEXIF and be done with it.

**Comment by emericg** [comment]
Hi,
I have a fork of libexif with a CMake build system here: https://github.com/emericg/libexif
You can see it in action here https://github.com/emericg/OffloadBuddy/blob/master/contribs/contribs.py
The only setback is that gettext is disabled, I didn't really look into it since I don't use it anyway. Other than that, it's a really simple patch. If someone is interested it's probably easy to finish it properly.

It works great on every platforms, including windows with MSVC, and you can (very) easily plug that onto AppVeyor (that's why I did it). Setting up autotools and cygwin on windows is just a backward solution that would have took me a couple of days of pain, without even speaking of making it work on remote CI services. The CMake file took an hour of work...

Hope that helps.

**Comment by levicki** [comment]
@emericg You sir, are awesome. Hopefully @dfandrich will consider merging CMake from your fork provided that gettext is an easy fix as you say it should be.

**Comment by dfandrich** [comment]
I'm still opposed to supporting two parallel build systems.

**Comment by emericg** [comment]
I'm sure you are. This wasn't a pull request, if anyone is interested they can just use the fork.
Maintaining two build system is indeed error prone, but sticking with autotools in an era of heavy multiplatform and cross compilation may not be a practical idea either.

**Comment by levicki** [comment]
To be honest, I was hoping that @dfandrich would consider migrating to CMake from autotools now that someone else already did most of that work. Sadly, it seems like this issue will be closed as "Works for me".

As for me, I have already switched to TinyEXIF and that's what is going to be credited in my application about dialog and documentation instead of this project.
