### ISSUE TITLE
Wrong offset?

### ISSUE THREAD

**Issue by kobe2000** [libexif/libexif#79]
Hi

I used libexif to read the following jpg by function `exif_data_new_from_data` but failed
![exif_90](https://user-images.githubusercontent.com/13567991/136485827-3cb1b386-e3b8-458e-b3fc-12bdffc6e9ea.jpg)

After debugging through source code, I found the offset(10, 4) in this line maybe wrong, I am not very certain of it though.
https://github.com/libexif/libexif/blob/3a1ce47d815361dc839f1113821b9eb6148df714/libexif/exif-data.c#L890

**Comment by msmeissn** [comment]
did it work before? e.g. is this recent breakage?

**Comment by shmuelk** [comment]
It is also good in version 0.6.22.

The breakage in 0.6.23 is in exif_data.c line 890.

The current code is `if ((ds >= 10) && !memcmp (d+4, ExifHeader, 6))`

The code should be `if ((ds >= 10) && !memcmp (d+3, ExifHeader, 6))`, (i.e. **+3** instead of **+4**)

At that point in the code d is pointing at a byte 0f 0xe1.

**Comment by msmeissn** [comment]
you are right, d does not point at FF but at E1 at the time of check. adjusted inGIT
